### ISSUE TITLE
Mobile Vulkan for Oculus Quest 2 ?

### ISSUE THREAD

**Issue by motorsep** [GodotVR/godot_oculus_mobile#124]
Is there any chance we'll see mobile Vulkan renderer support in Godot to take full advantage of Oculus Quest 1/2 hardware ?

**Comment by m4gr3d** [comment]
@motorsep Yes! Support for it is on our roadmap will be coming alongside Godot 4.0 sometimes in mid 2021.
I'll close this issue since we're already tracking that effort but feel free to continue the conversation here if you have more questions.

Thanks!

**Comment by ShawkMusic** [comment]
How is support for Vulkan coming along?
