### ISSUE TITLE
64bit Android binaries for Oculus Quest ?

### ISSUE THREAD

**Issue by motorsep** [GodotVR/godot_oculus_mobile#125]
Does Godot build 64bit binaries for Oculus Quest 1/2 ?

**Comment by BenMcLean** [comment]
yes https://docs.godotengine.org/en/stable/development/compiling/compiling_for_android.html

**Comment by m4gr3d** [comment]
@motorsep The Quest plugin binaries are prebuilt and can be retrieved from the [release page](https://github.com/GodotVR/godot_oculus_mobile/releases). The AAR binary contains both 32 and 64bit binaries.

**Comment by m4gr3d** [comment]
@motorsep You can follow the instructions on the [`README`](https://github.com/GodotVR/godot_oculus_mobile/releases) to find out how to install the binary in your Godot project.
