### ISSUE TITLE
VR framework for Godot ?

### ISSUE THREAD

**Issue by motorsep** [GodotVR/godot_oculus_mobile#126]
Are there any plans to offer VR framework for Godot ? 

By that I mean out of the box gameplay/input codebase that provides motion controllers support (input mapping, hand tracking/controller tracking switch, placeholder for skeletal mesh hand models with basic hand poses, basic interaction with objects in VR using motion controllers, etc.), automatic HMD height calibration, HMD type detection, Guardian boundary support, a few types of VR locomotions (blink, dash, standard WASD movement with orientation to HMD).

This would help folks coming from different engines (UE4 in particular; folks who mostly used to work with Blueprints), who aren't that skilled in tackling lower level programming, to jump start development/prototyping their VR projects in Godot.

**Comment by m4gr3d** [comment]
I believe [@NeoSpark314's toolkit](https://github.com/NeoSpark314/godot_oculus_quest_toolkit) fits that bill.

**Comment by m4gr3d** [comment]
@motorsep The [Godot XR discord](https://discord.gg/9UHYHcM) is also a good place to find more about available resources for VR development in Godot!

**Comment by BastiaanOlij** [comment]
We also have https://github.com/GodotVR/godot-xr-tools, but it's getting a little dated :)
