### ISSUE TITLE
Controller positions mishandle worldscale in versions since v3.0.1

### ISSUE THREAD

**Issue by goatchurchprime** [GodotVR/godot_oculus_mobile#133]
I think there's been a regression on https://github.com/GodotVR/godot_oculus_mobile/issues/103

I am using the precompiled (and later) version of the godot_ovrmobile available here:  https://github.com/NeoSpark314/godot_oculus_quest_toolkit/tree/master/addons/godot_ovrmobile

Set the world_scale to 2 and your controllers are once again high up above you.  This doesn't happen with the v3.0.1 assetlib version.

**Comment by NeoSpark314** [comment]
I think if this does not happen with the v3.0.1 asset lib version it is probably only an issue with the version used in the toolkit. The toolkit version is still based on 1.0 of the godot_oculus_mobile plugin.

**Comment by goatchurchprime** [comment]
Looks like it's because the godot_ovrmobile committed with the OQ_Toolkit is very old. It's hard to tell this because its files have been touched recently.  It would be nice to bring it up to date. I don't know what the reasons for not doing so are.
