### ISSUE TITLE
ovr_display.get_supported_display_refresh_rates() returns only 60hz and 72hz on Oculus Quest 2

### ISSUE THREAD

**Issue by mikotalik** [GodotVR/godot_oculus_mobile#136]
While tinkering with the Oculus Mobile Demo I noticed that it's running in 72hz mode on the Quest 2 despite the line setting it to 90hz if ovr_system.is_oculus_quest_2_device() is True:

This line:
`print("Display refresh rates: " + str(ovr_display.get_supported_display_refresh_rates()))`
prints [60,72]
and not [60,72,90] as it should
(and it should list even the 120hz mode which you can turn on in experimental settings on the Quest 2)

I'm running the newest v31 Quest OS version and I'm using the 3.0.1 version of the plugin from where the example is

**Comment by Wavesonics** [comment]
Probably you are missing the manifest declaration that you support Quest 2

**Comment by mikotalik** [comment]
After adding this line into AndroidManifest.xml, it still does not work. I'm probably missing something:

`
<meta-data android:name="com.oculus.supportedDevices" android:value="quest|quest2"/>
`

I got it from https://developer.oculus.com/documentation/native/android/mobile-native-manifest/

**Comment by mikotalik** [comment]
I probably found the issue. I was not using custom build. Enabling it throws error `General error during semantic analysis: Unsupported class file major version 60`
which probably means I have to upgrade Java. Closing
