### ISSUE TITLE
Add support for Passthrough API

### ISSUE THREAD

**Issue by walking-octopus** [GodotVR/godot_oculus_mobile#140]
See [developer.oculus.com/documentation/unity/unity-passthrough](https://developer.oculus.com/documentation/unity/unity-passthrough/) for reference.

**Comment by m4gr3d** [comment]
Passthrough support was already added to the [Godot OpenXR plugin](https://github.com/GodotVR/godot_openxr).

Oculus has [deprecated its vrapi API](https://www.roadtovr.com/oculus-openxr-shift-unity-unreal-engine/) upon which this plugin is built, so there should be no further updates to this plugin going forward.

**Comment by walking-octopus** [comment]
Thanks! Most of the documentation didn't mention this got deprecated. Have a good day!

**Comment by m4gr3d** [comment]
The OpenXR plugin got stable not too long ago, so we're still in the process of updating and refactoring the main Godot source code accordingly and as a result this plugin got inadvertently neglected.

Once we complete the update to the main Godot Engine code, we'll update the documentation accordingly.

Thanks!
