### ISSUE TITLE
Android Daydream VR

### ISSUE THREAD

**Issue by kmare** [GodotVR/godot_oculus_mobile#19]
I know this is about the GearVR, but as far as I understand it, Daydream VR should be pretty similar. Is it possible for this code base to support it as well or would it need a different approach?

Thank you in advance!

**Comment by Paritosh97** [comment]
Daydream and Cardboard or Google VR won't be implemented as a GDNative
module, we plan to bind it directly to the core(somewhat similar to the
Native mobile interface)
I did make a start to it, but there's a long way to go.

**Comment by kmare** [comment]
Thank you for your answer and your work. Did you upload anything to a repo that I could check out?

**Comment by Paritosh97** [comment]
[https://github.com/Paritosh97/godot/tree/google_vr/modules/google_vr](url)
There is a lot of stuff yet to be implemented, most of the code is simply copied from Native mobile.

**Comment by m4gr3d** [comment]
Closing this issue since this repo primarily focuses on the Oculus mobile devices.
