### ISSUE TITLE
Rename repo to godot_oculus_mobile

### ISSUE THREAD

**Issue by m4gr3d** [GodotVR/godot_oculus_mobile#21]
The [Oculus mobile SDK](https://developer.oculus.com/downloads/package/oculus-mobile-sdk/) powers the GearVR, Oculus Go, and upcoming Oculus Quest headsets.
As such, it'd be more appropriate to rename this repo to reflect that fact. The current name might confuse users and contributors as well.

**Comment by m4gr3d** [comment]
@BastiaanOlij Thoughts?

**Comment by DEF7** [comment]
I second this.

**Comment by BastiaanOlij** [comment]
With the Go and Quest, yes I will be doing this soon. Have a few more things to finish before I'm back on this but the rename makes a lot of sense

**Comment by BastiaanOlij** [comment]
Ok, I've renamed this but not done any more changes to the repo itself. I'm still working on #20 in which I did add a bit more descriptions. 

Upstream we have to finish https://github.com/godotengine/godot/pull/27010 first so we can get proper access to our viewport stuff.

I'm also working on this: https://github.com/godotengine/godot/pull/27527 which should help out loads here as well.

**Comment by m4gr3d** [comment]
Sounds good. I'm still getting up to speed on Godot's interface architecture. Once I do, I should be able to help complete #20.
