### ISSUE TITLE
Update the README

### ISSUE THREAD

**Issue by creikey** [GodotVR/godot_oculus_mobile#25]
With the [godot PR](https://github.com/godotengine/godot/pull/29824) that the readme says was necessary for this asset to work being merged into the master of Godot, and with no issues in this repository remaining, the README should be updated to reflect the current state of this project and remove the `<wip>` tags

**Comment by m4gr3d** [comment]
Thanks for the reminder @creikey. I'll push a PR shortly to update the readme.

**Comment by m4gr3d** [comment]
Fixed by PR #30.
