### ISSUE TITLE
No lighting rendered

### ISSUE THREAD

**Issue by NeoSpark314** [GodotVR/godot_oculus_mobile#33]
With the current master and the demo application I get no lighting in the demo scene only black geometry (emissive material also seems not to work, but the panorama seems to be correctly rendered)

![quest_bug_noLighting_01 09 2019_small](https://user-images.githubusercontent.com/1610621/62323212-149ecb80-b4a7-11e9-9f57-8ac79214e4de.jpg)

**Comment by m4gr3d** [comment]
@NeoSpark314 Stereo rendering is being tracked by issue #32, so can you update this bug's title accordingly.

Regarding stereo rendering, I've found the cause of the issue and am resolving it in commit 39090dff5ef710c713e6ef318302e167131b842c, but that unveiled another clipping issue that I'm looking into (i.e: objects don't render unless close to the headset).

**Comment by NeoSpark314** [comment]
I did some further testing. It seems to be an issue with export and with the GLES2 renderer. Exporting with GLES3 looks fine from a lighting perspective. Also it is probably not related to the oculus mobile plugin. When exporting for linux x86_64 the GLES2 render version also renders black (but it works fine in the editor).

**Comment by NeoSpark314** [comment]
This issue was fixed by https://github.com/godotengine/godot/pull/31062 in godot master.
