### ISSUE TITLE
Enable customization of the Oculus mobile runtime parameters

### ISSUE THREAD

**Issue by m4gr3d** [GodotVR/godot_oculus_mobile#35]
Add a set of api to enable customization of the Oculus mobile runtime parameters:
- [x] cpu/gpu level
- [x] fixed foveated rendering (FFR)
- [x] render target size
- [x] 72 / 60 Hz mode
- [x] swap interval
- [x] extra latency mode

**Comment by ajhager** [comment]
Hi @m4gr3d are you actively working on this ticket? I would love to jump in and work on these features, but I don't want to duplicate work.

**Comment by m4gr3d** [comment]
@ajhager I haven't started working on this issue, so feel free to jump in :)

Do you have a design in mind for how to approach this task?
Some of the parameters listed above can be dynamically changed during runtime, while others have to be set when the vrapi is initialized, so we have to ensure this is still possible on Godot.
In addition, we should be able to set and update the parameters both from the Android java layer, and from Godot scripts (gdscript, nativescript).

To that end, I was considering leveraging Godot's properties and notifications.
For example, the parameters would be written to Godot's properties (either via the Android java layer or Godot scripts), and then a notification would be fired to broadcast that the Oculus mobile parameters have been updated. 
The Oculus mobile plugin would listen for that notification, then retrieve and apply the updated set of parameters.

**Comment by ajhager** [comment]
I did not have a design in mind, so I appreciate any guidance. We want to be able to support our games on the Quest and Go so we thought the best way would be to help improve the library. Can I ask questions here?

**Comment by m4gr3d** [comment]
Sounds good, and yes this is a good place to ask questions!

**Comment by NeoSpark314** [comment]
@m4gr3d: To me this sounds like a good idea. The only advantage of the single class approach I see is to keep the logical grouping from VrApi.h; but I agree that it would be much easier to document and use if everything that makes sense during runtime can be accessed via a single GDNative class. I think this would also make it easier to expose convenicen functions like you did for `get_supported_display_refresh_rates` as there is no ambiguity to where to place these functions.

**Comment by m4gr3d** [comment]
@NeoSpark314 I've pushed PR #44 based on our discussion. I'd appreciate any feedback!

**Comment by NeoSpark314** [comment]
Yes; I'll read through your PR and note in there what comes to my mind.

**Comment by m4gr3d** [comment]
Fixed by PR #44 which is blocked by [godotengine/godot PR #32064](https://github.com/godotengine/godot/pull/32064).
