### ISSUE TITLE
Unable to restart Godot apps

### ISSUE THREAD

**Issue by m4gr3d** [GodotVR/godot_oculus_mobile#37]
It's likely that we're not properly shutting down the godot engine when using Oculus 'Quit' interface. If using Android Studio's logcat, you can see that the app process is still running.

Force quitting the app (using the adb command, or Android Studio) allows the app to properly restart.

Repro steps:

1. Install and launch a Godot app on an Oculus device
2. Exit the app using the controller's home button, and close it by selecting 'Quit' on the **Paused** prompt.
3. Launch the app again. 

Result:
The app will hang while trying to launch (black screen on Oculus Go, and black screen with loading dot on Oculus Quest).

**Comment by zlsa** [comment]
Oculus does something unusual when quitting. I added event handlers for "requesting quit" and "focus lost", and neither of them are called when clicking the "quit" button in the Oculus UI.

**Comment by m4gr3d** [comment]
@zlsa they perform the typical Android lifetime process when quitting: the app goes through onPause -> onStop -> on destroy.
It's the Godot native layer that's not cleaned up properly. Some of the native components are left running in the process, so when you try to restart, the app hangs since the components are in an invalid state.

**Comment by zlsa** [comment]
Huh, I was mistaken. I remember having the exact same issue with Unity right when the Go came out, so I incorrectly assumed it was the same issue.

Thanks for the clarification!

**Comment by m4gr3d** [comment]
No problem 😊.

There's a quick fix which is to force destroy the Android process when the app quit. This is not clean since you're suddenly killing the app, preventing any cleanup operations from completing.
I'll go with that solution first to unblock since the true fix is a lot more complex: tracing the native components that are initialized on startup, and ensure that they're properly stopped when the app stops.

**Comment by zlsa** [comment]
A bit off-topic, but is there a way to perform the equivalent of Java's `System.exit(0)` in Godot? I don't see any way to force-quit a Godot app from GDScript.

**Comment by m4gr3d** [comment]
Seems like that can be done by using [OS#kill](https://docs.godotengine.org/en/3.1/classes/class_os.html#class-os-method-kill) and [OS#get_process_id](https://docs.godotengine.org/en/3.1/classes/class_os.html#class-os-method-get-process-id).

**Comment by m4gr3d** [comment]
A temp solution was merged in master, so I'm updating the title and category accordingly.

**Comment by m4gr3d** [comment]
Closing this issue as it's been replaced by [Godot#31541](https://github.com/godotengine/godot/issues/31541).
