### ISSUE TITLE
Config GDScript Classes only valid after enter_vr_mode()

### ISSUE THREAD

**Issue by NeoSpark314** [GodotVR/godot_oculus_mobile#43]
I just noticed that there is no check if the ovr mobile context is NULL at https://github.com/GodotVR/godot_oculus_mobile/blob/36393808d159bb7e0a495f7038b0f67790702aa3/src/config/config_common.h#L30

and that only after `bool OvrMobileSession::enter_vr_mode()` is called (https://github.com/GodotVR/godot_oculus_mobile/blob/36393808d159bb7e0a495f7038b0f67790702aa3/src/ovr_mobile_session.cpp#L254)  it gets initialized.

The missing check leads to the call returning unexpected values; but I think this can be fixed by checking and returning an empty godot_variant (maybe with api->godot_variant_new_nil). Or there is a better way to return errors back to the user?

But this led to slighly more complex issue and there should also be a way for the user to check or know if calls are valid because for example at the moment it is not possible to call the Config API in the GDScript
`func _ready():`
after initializing the VR interface but only after the first time
`void OvrMobileSession::process()` is called. Maybe it would be valid to call `bool OvrMobileSession::enter_vr_mode()`already from the initialize() but I don't know the android application lifecycle.

In addition `void OvrMobileSession::exit_vr_mode()` is called when the application goes to sleep; when it wakes up again the first time
`func _process(delta)`
is executed it is again invalid to call the Config classes as the ovr mobile context is still NULL (for the second call it seems to be everything is well intialized again)

**Comment by m4gr3d** [comment]
Fixed by PR #44 which is blocked by [godotengine/godot PR #32064](https://github.com/godotengine/godot/pull/32064).
