### ISSUE TITLE
Quest Normal Maps are inverted

### ISSUE THREAD

**Issue by chrisbare** [GodotVR/godot_oculus_mobile#56]
I'm experimenting with Godot and the Oculus Quest. So far it's working very well, but I noticed that the normal maps on the PC are inverted on the Quest.

Bastiaan Olij -  Sounds to me like an issue with how the normal map is converted, really weird.
Best raise an issue on the godotvr github page for the plugin.

**Comment by NeoSpark314** [comment]
Did you check that under ProjectSettings->General->Rendering->Quality->Shading the Mobile Fallbacks (especially vertex lighting) are turned off. Else: do you have a screenshot? 

![Screenshot from 2019-10-06 12-41-17](https://user-images.githubusercontent.com/1610621/66538160-7c1a6c80-eb23-11e9-9b88-b6d07772de1a.png)

**Comment by chrisbare** [comment]
I did not know about those options and they seem to be enabled by default. Disabling them makes the Quest behave the same as the PC. Thank you for pointing out these settings.

**Comment by NeoSpark314** [comment]
Great to hear that it solved your problem. This is definitely something that should be well documented for the release as it is not very obvious. I also ran into this when starting to deploy for oculus quest.

**Comment by m4gr3d** [comment]
Seems like the issue was resovled. Feel free to reopen if not.
