### ISSUE TITLE
CMake Error: CMake was unable to find a build program corresponding to "Ninja".

### ISSUE THREAD

**Issue by lobinuxsoft** [GodotVR/godot_oculus_mobile#69]
Hello, I was following @BastiaanOlij tutorial, and when compiling the plugin the following problem occurs:

C:\Users\Lobinux-Lenovo\Desktop\Godot_Quest\godot_oculus_mobile\build>cmake -GNinja ..
CMake Error at C:/Users/Lobinux-Lenovo/AppData/Local/Android/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:100 (message):
  Could not find toolchain file:
  C:\Users\Lobinux-Lenovo\AppData\Local\Android\Sdk\ndk/build/cmake/android.toolchain.cmake
Call Stack (most recent call first):
  CMakeLists.txt:49 (project)

CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

and tried to unclog and reinstall Cmake, reviewing the environment variables, but I didn't find any problem, if someone can help me I would be very grateful.

[CMakeCache.txt](https://github.com/GodotVR/godot_oculus_mobile/files/3822125/CMakeCache.txt)

**Comment by sigmaxipi** [comment]
You'll need to install the [Ninja build system](https://ninja-build.org/). I haven't done this for Windows but with Ubuntu, `sudo apt-get install ninja-build` worked.

**Comment by lobinuxsoft** [comment]
**@sigmaxipi** Thanks for the response, I will install **Ninja Build System** and try to compile again, when I do I will give an answer to close the issue.

**Comment by m4gr3d** [comment]
@sigmaxipi @lobinuxsoft Based on your descriptions, the `cmake/bin` directory was not added to your environment variable `PATH`, hence why `cmake` doesn't see it.

@lobinuxsoft You should find a `ninja.exe` file in your ` C:/Users/Lobinux-Lenovo/AppData/Local/Android/Sdk/cmake/3.10.2.4988404/bin` directory. Make sure to add that directory to the `PATH` environment variable. 
That step is also described in the [Setup guide](https://github.com/GodotVR/godot_oculus_mobile#android-sdk--ndk).

**Comment by lobinuxsoft** [comment]
@m4gr3d I did everything they told me to do, but it didn't work out so I opted to completely unravel Android Studio, erase all the environment variables, and reinstall everything from scratch ... if they work for me I will let you know so close this issue.

**Comment by m4gr3d** [comment]
@lobinuxsoft You can also validate that the `ninja.exe` binary is in the `cmake/<version_dir>/bin` directory. 
If it's, you can validate your environment variable setup by launching `cmd` (or `powershell`) and typing `ninja.exe`. If the command is recognized, then the environment `path` variable is properly setup.

Hope that helps!

ps: If you're just looking to get access to the prebuilt binaries, you can use [this project](https://github.com/GodotVR/godot-oculus-mobile-asset) instead.
We're still setting it up, but once it's done, the plugin will also be available in the Godot asset library.

**Comment by lobinuxsoft** [comment]
It is indeed a problem of environment variables, maybe where the SDK is installed, probe changing the environment variable but still does not recognize the ninja.exe file ... do not worry I will look for a way to fix it, thank you for Help, you can close this issue.

**Comment by m4gr3d** [comment]
Thanks for the update! Feel free to re-open if you are still having issues building.

**Comment by lobinuxsoft** [comment]
I found what my mistake was, it is the environment variable that points to the NDK directory ... the variable points to "[Android Path]\Sdk\ndk", but it was wrong, since there is also the version number as a folder, correctly it would be "[Android Path]\Sdk\ndk\20.1.5948944".
