### ISSUE TITLE
Detect Quest as Platform

### ISSUE THREAD

**Issue by SoapSpangledGames** [GodotVR/godot_oculus_mobile#77]
When testing and debugging, I have code paths that are enabled when running on my PC and on my Android tablet, and different code paths that are enabled when running on the Quest.  Is there a way to differentiate between the two platforms?

**Comment by NeoSpark314** [comment]
One potential solution for this is to set a global variable when you successfully initialized the "OVRMobile" ARVR interface as this will only be successful on the quest. But there are probably other ways too like calling `OS.get_name()`

**Comment by SoapSpangledGames** [comment]
OS.get_name() was my first thought, too, and would have been ideal, but it returns "Android" on the Quest.  Not seeing the forest for the trees, though, I completely overlooked using OVRMobile as a determinant.

Thank you.

**Comment by NeoSpark314** [comment]
glad to help
