### ISSUE TITLE
Add support for hand tracking

### ISSUE THREAD

**Issue by m4gr3d** [GodotVR/godot_oculus_mobile#78]
Version 12.0 of the Oculus mobile SDK adds support for hand tracking, so the feature should be included and exposed in the Godot plugin.

https://developer.oculus.com/documentation/quest/latest/concepts/mobile-vrapi-input-api/#hand-tracking

**Comment by m4gr3d** [comment]
Hand tracking support in the plugin was added in PR #80.
Support in Godot core is being added by https://github.com/godotengine/godot/pull/34977.

**Comment by NeoSpark314** [comment]
I think this is done now. Or do you see something else that would be required for the first version of hand tracking support?

**Comment by m4gr3d** [comment]
Nope, looks good to me!
