### ISSUE TITLE
High Level Networking API not working

### ISSUE THREAD

**Issue by Luzzotica** [GodotVR/godot_oculus_mobile#82]
I am attempting to use the high level networking API on my Quest and I am getting this error:

- At: drivers/unix/net_socket_posix.cpp:440:poll() - Condition ' !is_open() ' is true. returned: ERR_UNCONFIGURED
- **ERROR**: Condition ' !is_open() ' is true. returned: ERR_UNCONFIGURED

I am fairly certain this is due to me running this on the Quest. The game I am running works perfectly fine on my laptop.

After reading this:
https://developer.oculus.com/documentation/platform/latest/concepts/dg-p2p/?locale=en_US

I believe that there may be a special way to make networking connections using the quest that doesn't work with the built in methods already in place.

Am I on the wrong track? Is this something more global or is this problem arising because of the Quest like I am thinking?

If you need anymore information please let me know! Thank you!

**Comment by m4gr3d** [comment]
It's unlikely that this is Quest specific since the Quest just run Android.
Can you try testing on a regular Android phone and see if you're running into the same issue.

**Comment by Luzzotica** [comment]
Will do. I'll get back to you later today.

**Comment by Luzzotica** [comment]
Ok, looks like my issue was that I had a function called _init and that was giving me the weirdest errors, this was never as issue.
Sorry to bother, and thank you for the quick reply!
