### ISSUE TITLE
running on Mac OSX

### ISSUE THREAD

**Issue by dirkk0** [GodotVR/godot_oculus_mobile#91]
Hi,
  first of all: thanks for the effort you guys put in all of this!

Then: is this supposed to work for Godot 3.2 on Mac OSX?

I can export the VR Starter Tutorial successfully to the Oculus Quest and it starts, I hear the sound but I only see three dots in the headset.

Although it compiles and gets executed on the the Quest, there is an error in the output that says:
```
 core/math/quick_hull.cpp:401 - Condition "O == E" is true. Continuing.
 Can't open dynamic library: /Applications/Godot.app/Contents/MacOS/../Frameworks/libgodot_openvr.dylib, error: dlopen(/Applications/Godot.app/Contents/MacOS/../Frameworks/libgodot_openvr.dylib, 2): Library not loaded: @loader_path/OpenVR.framework/Versions/A/OpenVR
  Referenced from: /Applications/Godot.app/Contents/Frameworks/libgodot_openvr.dylib
  Reason: image not found.
 modules/gdnative/gdnative.cpp:483 - No valid library handle, can't get symbol from GDNative object
 modules/gdnative/nativescript/nativescript.cpp:1506 - No nativescript_init in "res://addons/godot-openvr/bin/osx/libgodot_openvr.dylib" found
```
Manually moving `libgodot_openvr.dylib` to `/Applications/Godot.app/Contents/Frameworks/` didn't help either.

What am I missing?
For the record - my machine is still on High Sierra.

Thanks for looking into this.

Best regards,
  Dirk

**Comment by m4gr3d** [comment]
Hi Dirk, based on the error message you're using the openvr plugin instead of using the Quest plugin.
Here's the one you should be using: https://godotengine.org/asset-library/asset/500

**Comment by dirkk0** [comment]
oh, I see, thank you!
This was probably because I downloaded the
https://github.com/GodotVR/godot_openvr_fps project.
Is there an Oculus Starter project for Godot?

**Comment by m4gr3d** [comment]
This repo has a demo project which can be used as a starter project under https://github.com/GodotVR/godot_oculus_mobile/tree/master/demo.

I'll close this issue since it seems to be resolved but feel free to re-open if you run into other issues.
For quick tips & advices the [Godot XR discord](https://discord.gg/9UHYHcM) is the recommended resource!

**Comment by dirkk0** [comment]
... worked like a charm, thank you!
